version: '3.7'

services:
  app:
    build:
      args:
        user: dridosh
        uid: 1000
      context: ./
      dockerfile: _docker/app/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    image: laravel_app
    container_name: lara_app


  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d/
    restart: unless-stopped
    ports:
      - 8876:80
    depends_on:
      - app
    container_name: lara_nginx


  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./_docker/sda/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 8101:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: lara_db



